### ISSUE TITLE
fixed abbreviated shape headers. 

### ISSUE THREAD

**Issue by famulare** [seattleflu/seattle-geojson#3]
CRA_NAME is currently abbreviated as CRA_NAM.
NEIGHBORHOOD_DISTRICT_NAME is NEIGHBO.

I don't love the long names but they are what we get from the city, so we should keep them.

**Comment by famulare** [comment]
I'm not sure if this is still a problem.  incidence-mapper now is fine with the abbreviated names as of 4ea044c4355bb40286dcc45481519a34ac3be775.  Your call if we change this and accept the `standard-level-names` pull request, @jotasolano

**Comment by jotasolano** [comment]
I'm personally fine with abbreviated names. @jameshadfield what's your take on this?

**Comment by jameshadfield** [comment]
Either is fine for me -- the viz currently uses the abbreviated names, but it should be a pretty simple change in the app if you choose to go with the longer names.

**Comment by famulare** [comment]
Thanks both. I'll close this now then and leave it alone.
