### ISSUE TITLE
Define SFS year 2 spatial domain from swab-and-send zips

### ISSUE THREAD

**Issue by famulare** [seattleflu/seattle-geojson#7]
SFS Year 2 has a hybrid spatial domain--recruitment and messaging focused in Seattle but accepting enrollees through retrospectives and swab-and-send from outside city limits.  For downstream analysis, we wanted to define a "canonical" spatial domain as `neighborhood_district_name` within seattle and `puma` outside seattle. This requires building a shape set with the right names, some choices about mapping zipcode onto neighborhood/puma, and defining a master lookup list for all data.

**Comment by famulare** [comment]
@trvrb @tsibley   I added a set of geojsons that form the "canonical" shape set for the SFS Year 2.  https://github.com/seattleflu/seattle-geojson/tree/master/sfs_domain_geojsons  Lat-long points are included, and I wiggled a few to be more population-weighted for pumas at the edge of the domain to make more reasonable auspice centroids. Take a look and let me know if you have any comments.

**Comment by tsibley** [comment]
@famulare Thanks. Are you using the `regional_name` of each geometry as the primary key in your models?

**Comment by famulare** [comment]
Yes!  Probably should’ve said that explicitly somewhere.

**Comment by trvrb** [comment]
@famulare @tsibley --- Thanks for this. https://github.com/seattleflu/seattle-geojson/blob/master/sfs_domain_geojsons/sfs_domain_neighborhood%2Bpuma.geojson looks great. I do have one question: what's the best way to lookup the "SFS domain" (neighborhood or puma) associated with a particular census tract?

It looks like it will take a while to get this natively exported as shipping view from ID3C and so I would plan to just make a mapping table as part of https://github.com/seattleflu/augur-build. @famulare, I would assume you're already doing this as part of incidence-mapper?

**Comment by famulare** [comment]
The lookup table is embedded in this tract level geojson: https://github.com/seattleflu/seattle-geojson/blob/master/sfs_domain_geojsons/2016_wa_censusTracts%2Bsfs_domain.geojson.   

The intended reference columns are `GEOID` (tract) and `PUMA` (which should be the 7 digit version per earlier discussions but is currently 5 #11), and `regional_name`.   `regional_name` is inherited from the Seattle Neighborhood District names or the PUMA name, but a few of the boundary regions are smaller than the PUMA and so the names could arguably be edited.
